### PR TITLE
Broadcast scalar input variable values to expected array structure

### LINKED ISSUE #541: Fix ASan-reported heap-buffer-overflow in BMI Python adapter tests
Discovered in the course of #536

> `cmake -S . -B build-asan2 -DCMAKE_BUILD_TYPE=Debug -DBOOST_ROOT=/opt/homebrew/opt/boost\@1.76/ -DBMI_C_LIB_ACTIVE=ON -D BMI_FORTRAN_ACTIVE:BOOL=ON -DCMAKE_CXX_FLAGS=-fsanitize=address -DCMAKE_C_FLAGS=-fsanitize=address`

```
./test/test_bmi_python --gtest_filter=Bmi_Py_Formulation_Test.get_response_0_a
Running main() from /Users/phil/Code/noaa/ngen/test/googletest/googletest/src/gtest_main.cc
Note: Google Test filter = Bmi_Py_Formulation_Test.get_response_0_a
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from Bmi_Py_Formulation_Test
[ RUN      ] Bmi_Py_Formulation_Test.get_response_0_a
Definition of "au" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-accepted.xml", line 123, overrides prefixed-unit "1.6605402e-45 kilogram"
Definition of "kt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 105, overrides prefixed-unit "1000000 kilogram"
Definition of "microns" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 416, overrides prefixed-unit "1e-15 second"
Definition of "ft" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 527, overrides prefixed-unit "1e-12 kilogram"
Definition of "yd" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 536, overrides prefixed-unit "8.64e-20 second"
Definition of "pt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 790, overrides prefixed-unit "1e-09 kilogram"
Definition of "at" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1259, overrides prefixed-unit "1e-15 kilogram"
Definition of "ph" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1889, overrides prefixed-unit "3.6e-09 second"
Definition of "nt" in "/Volumes/Cased/Code/noaa/ngen/build-asan2/UDUNITS-2/build/share/udunits/udunits2-common.xml", line 1898, overrides prefixed-unit "1e-06 kilogram"
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to parse out_units value -")
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to convert mm s^-1 to kg m^-2")
Invalid value of specific humidity with no supplied rel. humidity in ET calc. function:
Relative Humidity: -99.900000 percent
Specific Humidity: 0.009300 kg/kg
WARN: Unit conversion unsuccessful - Returning unconverted value! ("Unable to parse out_units value -")
=================================================================
==59431==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x000105d74418 at pc 0x000103c6f83c bp 0x00016dd47430 sp 0x00016dd46be8
READ of size 48 at 0x000105d74418 thread T0
    #0 0x103c6f838 in wrap_memcpy+0x13c (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838)
    #1 0x109eb14b4 in _contig_to_contig+0x28 (_multiarray_umath.cpython-311-darwin.so:arm64+0x10d4b4)
    #2 0x109e47d88 in raw_array_assign_array+0x2bc (_multiarray_umath.cpython-311-darwin.so:arm64+0xa3d88)
    #3 0x109e4886c in PyArray_AssignArray+0x324 (_multiarray_umath.cpython-311-darwin.so:arm64+0xa486c)
    #4 0x109e54260 in PyArray_NewCopy+0x38 (_multiarray_umath.cpython-311-darwin.so:arm64+0xb0260)
    #5 0x102496010 in pybind11::array::array(pybind11::dtype const&, pybind11::detail::any_container<long>, pybind11::detail::any_container<long>, void const*, pybind11::handle) numpy.h:743
    #6 0x1024951e4 in pybind11::array::array(pybind11::buffer_info const&, pybind11::handle) numpy.h:774
    #7 0x1024b0620 in pybind11::array_t<double, 16>::array_t(pybind11::buffer_info const&, pybind11::handle) numpy.h:1053
    #8 0x1024b00c4 in pybind11::array_t<double, 16>::array_t(pybind11::buffer_info const&, pybind11::handle) numpy.h:1053
    #9 0x102492fac in void models::bmi::Bmi_Py_Adapter::set_value<double>(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > const&, double*) Bmi_Py_Adapter.hpp:765
    #10 0x102439470 in models::bmi::Bmi_Py_Adapter::SetValue(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, void*) Bmi_Py_Adapter.hpp:535
    #11 0x1024cabe0 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1139
    #12 0x1024c8bd4 in realization::Bmi_Py_Formulation::get_response(long, long) Bmi_Py_Formulation.cpp:105
    #13 0x1021dbb60 in Bmi_Py_Formulation_Test_get_response_0_a_Test::TestBody() Bmi_Py_Formulation_Test.cpp:409
    #14 0x102408bc4 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #15 0x102370294 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #16 0x10236fe64 in testing::Test::Run() gtest.cc:2674
    #17 0x102372704 in testing::TestInfo::Run() gtest.cc:2853
    #18 0x102375698 in testing::TestSuite::Run() gtest.cc:3012
    #19 0x1023998f0 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #20 0x102416c58 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #21 0x1023989b0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #22 0x1023984c0 in testing::UnitTest::Run() gtest.cc:5444
    #23 0x102429c70 in RUN_ALL_TESTS() gtest.h:2293
    #24 0x102429bcc in main gtest_main.cc:51
    #25 0x10305d088 in start+0x204 (dyld:arm64e+0x5088)

0x000105d74418 is located 0 bytes to the right of 8-byte region [0x000105d74410,0x000105d74418)
allocated by thread T0 here:
    #0 0x103ca6018 in wrap__Znam+0x74 (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x4e018)
    #1 0x102585554 in std::__1::shared_ptr<double> realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::as_c_array<double, std::__1::__wrap_iter<double*> >(std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:995
    #2 0x10257f248 in std::__1::shared_ptr<void> realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::get_values_as_type<std::__1::__wrap_iter<double*> >(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::__wrap_iter<double*>, std::__1::__wrap_iter<double*>) Bmi_Module_Formulation.hpp:1022
    #3 0x1024ca464 in realization::Bmi_Module_Formulation<models::bmi::Bmi_Py_Adapter>::set_model_inputs_prior_to_update(double const&, long) Bmi_Module_Formulation.hpp:1131
    #4 0x1024c8bd4 in realization::Bmi_Py_Formulation::get_response(long, long) Bmi_Py_Formulation.cpp:105
    #5 0x1021dbb60 in Bmi_Py_Formulation_Test_get_response_0_a_Test::TestBody() Bmi_Py_Formulation_Test.cpp:409
    #6 0x102408bc4 in void testing::internal::HandleSehExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2599
    #7 0x102370294 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) gtest.cc:2635
    #8 0x10236fe64 in testing::Test::Run() gtest.cc:2674
    #9 0x102372704 in testing::TestInfo::Run() gtest.cc:2853
    #10 0x102375698 in testing::TestSuite::Run() gtest.cc:3012
    #11 0x1023998f0 in testing::internal::UnitTestImpl::RunAllTests() gtest.cc:5870
    #12 0x102416c58 in bool testing::internal::HandleSehExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2599
    #13 0x1023989b0 in bool testing::internal::HandleExceptionsInMethodIfSupported<testing::internal::UnitTestImpl, bool>(testing::internal::UnitTestImpl*, bool (testing::internal::UnitTestImpl::*)(), char const*) gtest.cc:2635
    #14 0x1023984c0 in testing::UnitTest::Run() gtest.cc:5444
    #15 0x102429c70 in RUN_ALL_TESTS() gtest.h:2293
    #16 0x102429bcc in main gtest_main.cc:51
    #17 0x10305d088 in start+0x204 (dyld:arm64e+0x5088)

SUMMARY: AddressSanitizer: heap-buffer-overflow (libclang_rt.asan_osx_dynamic.dylib:arm64e+0x17838) in wrap_memcpy+0x13c
Shadow bytes around the buggy address:
  0x007020bce830: fa fa fd fa fa fa fd fa fa fa 00 fa fa fa fd fa
  0x007020bce840: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce850: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce860: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce870: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
=>0x007020bce880: fa fa 00[fa]fa fa fd fa fa fa 00 05 fa fa fd fa
  0x007020bce890: fa fa fd fa fa fa fd fa fa fa fd fa fa fa 04 fa
  0x007020bce8a0: fa fa 04 fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce8b0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
  0x007020bce8c0: fa fa fd fa fa fa fd fa fa fa fd fd fa fa fd fa
  0x007020bce8d0: fa fa fd fa fa fa fd fa fa fa fd fa fa fa fd fa
Shadow byte legend (one shadow byte represents 8 application bytes):
  Addressable:           00
  Partially addressable: 01 02 03 04 05 06 07 
  Heap left redzone:       fa
  Freed heap region:       fd
  Stack left redzone:      f1
  Stack mid redzone:       f2
  Stack right redzone:     f3
  Stack after return:      f5
  Stack use after scope:   f8
  Global redzone:          f9
  Global init order:       f6
  Poisoned by user:        f7
  Container overflow:      fc
  Array cookie:            ac
  Intra object redzone:    bb
  ASan internal:           fe
  Left alloca redzone:     ca
  Right alloca redzone:    cb
==59431==ABORTING
Abort trap: 6
```

### PR DESCRIPTION
**Pull request by PhilMiller**
Extracted from #534 to more directly clear the way for #536

Fixes #541, #549

Fixes a number of invalid memory access resulting from the receiving model trying to read more data that the framework is providing.

When built and configured with `export CXXFLAGS="-g -fsanitize=address" CFLAGS="-g -fsanitize=address" FFLAGS="-g"`, `ctest` reports as follows

* Before:
```
98% tests passed, 14 tests failed out of 821

[...]

The following tests FAILED:
	233 - Bmi_Fortran_Formulation_Test.GetOutputLineForTimestep_0_a (Subprocess aborted)
	291 - Bmi_Py_Formulation_Test.get_response_0_a (Subprocess aborted)
	292 - Bmi_Py_Formulation_Test.get_response_0_b (Subprocess aborted)
	294 - Bmi_Py_Formulation_Test.GetOutputLineForTimestep_0_a (Subprocess aborted)
	295 - Bmi_Py_Formulation_Test.GetOutputLineForTimestep_0_b (Subprocess aborted)
	315 - Bmi_Multi_Formulation_Test.GetOutputLineForTimestep_1_a (Subprocess aborted)
	316 - Bmi_Multi_Formulation_Test.GetOutputLineForTimestep_1_b (Subprocess aborted)
	460 - Bmi_Fortran_Formulation_Test.GetOutputLineForTimestep_0_a (Subprocess aborted)
	518 - Bmi_Py_Formulation_Test.get_response_0_a (Subprocess aborted)
	519 - Bmi_Py_Formulation_Test.get_response_0_b (Subprocess aborted)
	521 - Bmi_Py_Formulation_Test.GetOutputLineForTimestep_0_a (Subprocess aborted)
	522 - Bmi_Py_Formulation_Test.GetOutputLineForTimestep_0_b (Subprocess aborted)
	542 - Bmi_Multi_Formulation_Test.GetOutputLineForTimestep_1_a (Subprocess aborted)
	543 - Bmi_Multi_Formulation_Test.GetOutputLineForTimestep_1_b (Subprocess aborted)
```

* After:
```
100% tests passed, 0 tests failed out of 821
```

## Changes

- A variable provided as a scalar value from a source will be broadcast to an array of the recipient model's expected size.

## Notes

- This will entail broader discussion around #551 

## Checklist

- [x] PR has an informative and human-readable title
- [x] Changes are limited to a single goal (no scope creep)
- [x] Code can be automatically merged (no conflicts)
- [x] Code follows project standards (link if applicable)
- [x] Passes all existing automated tests
- [x] Any _change_ in functionality is tested
- [x] New functions are documented (with a description, list of inputs, and expected output)
- [x] Placeholder code is flagged / future todos are captured in comments
- [x] Project documentation has been updated (including the "Unreleased" section of the CHANGELOG)
- [x] Reviewers requested with the [Reviewers tool](https://help.github.com/articles/requesting-a-pull-request-review/) :arrow_right:

### CODE REVIEW

**Comment by PhilMiller** [comment]
@hellkite500 I opened this PR at Matt's request to separate it for easier review from #534. As we discussed, there need to be better guard rails and/or reporting that this is happening, so that it doesn't silently trip anyone up.

**Comment by PhilMiller** [comment]
The added warning about the broadcasting appears this many times in the tests:
```
$ grep broadcasting output | sort | uniq -c | sort -rn
1086 544: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
1086 543: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
1086 317: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
1086 316: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 544 522: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 544 295: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 543 541: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 543 462: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 543 314: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
 543 235: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 539: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 538: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 536: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 312: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 311: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  78 309: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 534: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 519: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 458: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 307: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 292: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
  39 231: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 542: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 537: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 535: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 459: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 315: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 310: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 308: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   2 232: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 540: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 533: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 521: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 518: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 461: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 460: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 457: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 313: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 306: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 294: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 291: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 234: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 233: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
   1 230: ngen Warning: broadcasting variable 'GRID_VAR_1' from scalar to expected array
```

File: include/realizations/catchment/Bmi_Module_Formulation.hpp [hunk 1]
```diff
@@ -1113,16 +1113,20 @@ namespace realization {
...
                 int varItemSize = get_bmi_model()->GetVarItemsize(var_name);
+                int numItems = nbytes / varItemSize;
+                assert(nbytes % varItemSize == 0);
+
                 std::shared_ptr<void> value_ptr;
                 // Finally, use the value obtained to set the model input
                 std::string type = get_bmi_model()->get_analogous_cxx_type(get_bmi_model()->GetVarType(var_name),
                                                                            varItemSize);
-                if (varItemSize != get_bmi_model()->GetVarNbytes(var_name)) {
+                if (numItems != 1) {
```
Comment (mattw-nws) [inline include/realizations/catchment/Bmi_Module_Formulation.hpp:1129]: Okay I wondered this also looking at #534 ... for argument's sake, when are these two conditionals not equivalent? When the model reports the wrong values for one or the other? Or is the new version just clearer?

Comment (PhilMiller) [reply include/realizations/catchment/Bmi_Module_Formulation.hpp:1129]: I changed this for clarity and to avoid repetitive calls. It should be functionally equivalent.

Algebra-wise, this is dividing both sides by `varItemSize`. The added `assert` above guards against a bug that makes it not perfectly divisible. I'm trusting that none of these will return negative values. So, that leaves `varItemSize == 0` I guess, which would be equally non-sensical.

**Comment by PhilMiller** [comment]
(rebased, and we now get 100% test pass)

File: include/realizations/catchment/Bmi_Module_Formulation.hpp (hunk 1 above)
Comment (mattw-nws) [reply include/realizations/catchment/Bmi_Module_Formulation.hpp:1129]: Oi... yeah there's probably a suite of things like that we _could_ call against BMI models that we should assert true on...e.g. multiplying out get_grid_shape by the get_var_itemsize = get_var_nbytes... something to think about for later, though that would tend to get expensive. The `%` above is pretty cheap though I think.

**Comment by mattw-nws** [comment]
This seems perfectly sound other than the philosophical question of whether we _should_ be doing it... which (for the record) remains undecided. Approving this in any case though because the existing code produces undefined behavior which is decidedly worse.

**Review by mattw-nws — APPROVED** [review]
